"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 2
final_space = true

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
    background = "transparent"
    foreground = "#ffffff"
    style = "plain"
    template = " {{ if .WSL }}WSL at {{ end }}{{.Icon}} "
    type = "os"

    [blocks.segments.properties]
      alpine = ""
      arch = ""
      centos = ""
      debian = ""
      elementary = ""
      fedora = ""
      gentoo = ""
      linux = ""
      macos = ""
      manjaro = ""
      mint = ""
      opensuse = ""
      raspbian = ""
      ubuntu = ""
      windows = ""
      wsl = ""

  [[blocks.segments]]
  type = "shell"
  style = "plain"
  foreground = "#E06C75"
  template = "  {{ .Name }}"

[blocks.segments.properties.mapped_shell_names]
bash = "Bash"
cmd = "Cmd"
powershell = "Shell"
pwsh = "Shell"

  [[blocks.segments]]
  type = "git"
  style = "plain"
  foreground = "#F3C267"
  foreground_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}#FF9248{{ end }}",
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#ff4500{{ end }}",
  "{{ if gt .Ahead 0 }}#B388FF{{ end }}",
  "{{ if gt .Behind 0 }}#B388FF{{ end }}"
]
  template = " {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} "

    [blocks.segments.properties]
    branch_max_length = 25
    fetch_stash_count = true
    fetch_status = true
    fetch_upstream_icon = true
    branch_icon = ''

[[blocks]]
type = "prompt"
alignment = "right"

  [[blocks.segments]]
  type = "status"
  style = "plain"
  foreground = "#b8ff75"
  foreground_templates = [ "{{ if gt .Code 0 }}#E06C75{{ end }}" ]
  template = " x{{ reason .Code }}"

  [[blocks.segments]]
  type = "executiontime"
  style = "diamond"
  foreground = "#b8ff75"
  foreground_templates = [ "{{ if gt .Code 0 }}#E06C75{{ end }}" ]
  template = " {{ .FormattedMs }} "

    [blocks.segments.properties]
    always_enabled = true
    style = "roundrock"

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
  type = "path"
  style = "plain"
  foreground = "#61AFEF"
  template = " {{ .Path }}"

    [blocks.segments.properties]
    style = "full"

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
  type = "root"
  style = "plain"
  foreground = "#E06C75"
  template = "!"

  [[blocks.segments]]
  type = "text"
  style = "plain"
  foreground = "#E06C75"
  template = "❯"

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}magenta{{end}}"
  ]
  background = "transparent"
  template = "❯ "
